### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by alouanemed** [RxSwiftCommunity/RxTheme#16] opened 2020-05-16 12:19 UTC
When profiling the app with instruments' Leaks, it shows that rxtheme leaked somewhere. I couldn't find the place exact, so I went and started generating memory graph using Xcode, and it shows this leak:
> runtime: Memory Issues - (1 leaked type): 13 instances of Swift closure context leaked

![image](https://user-images.githubusercontent.com/7117097/82119511-c07f8200-976e-11ea-866d-562ebffdc62d.png)
**instrument output**

checking some of those issues revealed that are linked to RxTheme. like this one below:
  taken from a Button class:

```
func makeUI() {
       
        themeService.rx
            .bind({ UIImage(color: $0.primary, size: CGSize(width: 1, height: 1)) }, to: rx.backgroundImage(for: .normal))
            .bind({ UIImage(color: $0.primary.withAlphaComponent(0.9), size: CGSize(width: 1, height: 1)) }, to: rx.backgroundImage(for: .selected))
            .bind({ UIImage(color: $0.primary.withAlphaComponent(0.6), size: CGSize(width: 1, height: 1)) }, to: rx.backgroundImage(for: .disabled))
            .disposed(by: rx.disposeBag)

```

As I am navigating through the other screens, the number pop's up to 100 Swift closure context leaked. Anyway to solve this? Thanks.

**Comment by wddwycc** [comment] 2020-05-16 12:35
hi @alouanemed , can you provide a sample project to reproduce the issue ?

**Comment by alouanemed** [comment] 2020-05-16 12:54
OKay, let me create one.

**Comment by wddwycc** [comment] 2020-06-02 03:46
@alouanemed  any progress ?

**Comment by alouanemed** [comment] 2020-06-02 09:33
@wddwycc I tried to reproduce the issue but couldn't. Most leaks are related to RxSwift (including RxTheme). I created this repo https://github.com/alouanemed/leakTest that resembles my project but haven't yet able to reproduce. let me give another try.

**Comment by wddwycc** [comment] 2020-06-22 13:20
I would close this one since it's not reproducable.

**Closed as completed by wddwycc** 2020-06-22 13:20 UTC
